import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/components/LenisProvider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <header className="sticky top-0 z-50 bg-white/80 backdrop-blur border-b">
        <nav className="max-w-6xl mx-auto px-6 h-14 flex items-center gap-6 text-sm">
          <Link href="/" className="font-medium">
            Celeste Di Forte
          </Link>
          <Link href="/proyectos" className="text-neutral-600 hover:text-black">
            Proyectos
          </Link>
        </nav>
      </header>
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
